apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:

spec:
  type: NodePort
  selector:
    app: guestbook

  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30801
