apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: antattackweb
  name: antattackweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: antattackweb
  template:
    metadata:
      labels:
        app: antattackweb
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: nginx