apiVersion: v1
kind: Service
metadata:
  name: antattackweb1
  labels:
    app: antattackweb1
spec:
  type: NodePort
  selector:
    app: antattackweb1

  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080