apiVersion: v1
kind: Service
metadata:
  name: antattack1
  labels:
    app: antattack1
spec:
  type: NodePort
  selector:
    app: antattack1

  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080