apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample1
  name: sample1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample1
  template:
    metadata:
      labels:
        app: sample1
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: nginx