apiVersion: v1
kind: Service
metadata:
  name: sample1
  labels:
    app: sample1
spec:
  type: NodePort
  selector:
    app: sample1

  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080